# fly.toml app configuration file generated for example-small-tree-1458 on 2025-12-02T21:14:56+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'example-small-tree-1458'
primary_region = 'arn'

[build]

[env]
  PORT = "3001" # add this

[http_service]
  internal_port = 3001 # ensure that this is same as PORT
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = '256mb'      # 关键修改：从 1gb 改为 256mb
  cpu_kind = 'shared'
  cpus = 1
